version: "3"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: degree_planner
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
      - ./scripts:/scripts
volumes:
  postgres-db-data:
    name: postgres-db-data